apiVersion: v1
kind: Namespace
metadata:
  name: java-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: java-demo
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: registry-vpc.cn-beijing.aliyuncs.com/microservice-demo/cartservice:1.0.1
          env:
          - name: dubbo.registry.address
            value: "nacos://nacos:8848"