apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: java-demo
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        ahasPilotAutoEnable: "on"
        ahasAppName: "java-demo-frontend"
        ahasNamespace: "default"
        armsPilotAutoEnable: "on"
        armsPilotCreateAppName: "java-demo-frontend"
    spec:
      containers:
        - name: frontend
          image: registry.cn-beijing.aliyuncs.com/microservice-demo/frontend:1.0.1
          ports:
          - containerPort: 8080
          env:
          - name: dubbo.registry.address
            value: "nacos://nacos:8848"
          - name: spring.cloud.nacos.discovery.server-addr
            value: "nacos:8848"
          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 64Mi
          #   limits:
          #     cpu: 200m
          #     memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: java-demo
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
  namespace: java-demo
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - name: http
    port: 8080
    targetPort: 8080
