apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: java-demo
spec:
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
        - name: nacos-standalone
          image: nacos/nacos-server:latest
          ports:
          - containerPort: 8848
          env:
          - name: PREFER_HOST_MODE
            value: "hostname"
          - name: MODE
            value: "standalone"
---
apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: java-demo
spec:
  type: ClusterIP
  selector:
    app: nacos
  ports:
  - name: http
    port: 8848
    targetPort: 8848