apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
  namespace: java-demo
spec:
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
      annotations:
        ahasPilotAutoEnable: "on"
        ahasAppName: "java-demo-product"
        ahasNamespace: "default"
        armsPilotAutoEnable: "on"
        armsPilotCreateAppName: "java-demo-product"
    spec:
      containers:
        - name: productservice
          image: registry.cn-beijing.aliyuncs.com/microservice-demo/productservice:1.0.1
          env:
          - name: spring.cloud.nacos.discovery.server-addr
            value: "nacos:8848"